import './globals.css'
import { Inter, Roboto } from 'next/font/google'

const roboto = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bitwise Technology',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://unpkg.com/@phosphor-icons/web"></script>
      </head>
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
