query($name: String!, $last: String!) { 
  more: user(login: $name) {
    repositories(first: 5, privacy: PUBLIC, after: $last) {
      totalCount,
      pageInfo {
        endCursor,
        hasNextPage
      }
      nodes {
        name,
        object(expression: "master") {
          ... on Commit {
            history {
              totalCount
              nodes {
                oid,
                messageHeadline
              }
            }
          }
        }
      }
    }
  }
}