query($name: String!) { 
  data: user(login: $name) {
    name,
    avatarUrl,
    login,
    repositories(first: 5, privacy: PUBLIC) {
      totalCount,
      pageInfo {
        endCursor,
        hasNextPage
      }
      nodes {
        name,
        object(expression: "master") {
          ... on Commit {
            history {
              totalCount
              nodes {
                oid,
                messageHeadline
              }
            }
          }
        }
      }
    }
  }
}